const RAW_REGISTRY = {
    "system_status": "active",
    "registry_version": "1.0.0",
    "nodes": [
        { "id": "neumorphic-design", "name": "Neumorphic Design", "url": "https://neumorphic.design/" },
        { "id": "fotor", "name": "Fotor", "url": "https://www.fotor.com/" },
        { "id": "soft-ui-library", "name": "Soft UI Library", "url": "https://katendeglory.github.io/soft-ui-library/" },
        { "id": "neumorphism-io", "name": "Neumorphism.io", "url": "https://neumorphism.io/#e0e0e0" },
        { "id": "css-box-shadow-examples", "name": "CSS Box Shadow Examples", "url": "https://getcssscan.com/css-box-shadow-examples" },
        { "id": "css-buttons-examples", "name": "CSS Buttons Examples", "url": "https://getcssscan.com/css-buttons-examples" },
        { "id": "css-checkboxes-examples", "name": "CSS Checkboxes Examples", "url": "https://getcssscan.com/css-checkboxes-examples" },
        { "id": "css-gradients", "name": "CSS Pro Gradients", "url": "https://csspro.com/css-gradients" },
        { "id": "svg-to-background-image", "name": "SVG to Background Image", "url": "https://csspro.com/svg-to-background-image-css" },
        { "id": "css-3d-buttons", "name": "CSS 3D Buttons", "url": "https://csspro.com/css-3d-buttons" },
        { "id": "best-css-button-generator", "name": "Best CSS Button Generator", "url": "https://www.bestcssbuttongenerator.com/" },
        { "id": "css-portal", "name": "CSS Portal", "url": "https://www.cssportal.com/" },
        { "id": "gradient-animator", "name": "Gradient Animator", "url": "https://www.gradient-animator.com/" },
        { "id": "transparent-textures", "name": "Transparent Textures", "url": "https://www.transparenttextures.com/" },
        { "id": "creative-hover-effects", "name": "Creative Hover Effects", "url": "https://wweb.dev/resources/creative-hover-effects" },
        { "id": "navigation-generator", "name": "Navigation Generator", "url": "https://wweb.dev/resources/navigation-generator" },
        { "id": "animated-css-backgrounds", "name": "Animated CSS Background Generator", "url": "https://wweb.dev/resources/animated-css-background-generator" },
        { "id": "css-box-shadow-generator", "name": "Minimamente CSS Box Shadow", "url": "https://www.minimamente.com/cssboxshadow/" },
        { "id": "jsfiddle", "name": "JSFiddle", "url": "https://jsfiddle.net/" },
        { "id": "w3schools-tryit", "name": "W3Schools TryIt", "url": "https://www.w3schools.com/howto/tryit.asp" },
        { "id": "codepen-new", "name": "CodePen New", "url": "https://codepen.io/pen/" },
        { "id": "codepen-trending", "name": "CodePen Trending", "url": "https://codepen.io/trending" },
        { "id": "freecodez-html", "name": "FreeCodez HTML", "url": "https://freecodez.com/create/html" },
        { "id": "uikit", "name": "UIkit", "url": "https://getuikit.com/" },
        { "id": "icones-js", "name": "Icônes", "url": "https://icones.js.org/" },
        { "id": "tabler-icons", "name": "Tabler Icons", "url": "https://tablericons.com/" },
        { "id": "bootstrap-icons", "name": "Bootstrap Icons", "url": "https://icons.getbootstrap.com/" },
        { "id": "fontawesome", "name": "Font Awesome Search", "url": "https://fontawesome.com/search" },
        { "id": "mingcute", "name": "MingCute Icons", "url": "https://www.mingcute.com/" },
        { "id": "iconduck", "name": "IconDuck", "url": "https://iconduck.com/" },
        { "id": "google-fonts-icons", "name": "Google Fonts Icons", "url": "https://fonts.google.com/icons" },
        { "id": "it-tools", "name": "IT Tools", "url": "https://it-tools.tech/" },
        { "id": "uiverse", "name": "Uiverse Elements", "url": "https://uiverse.io/elements" },
        { "id": "angrytools", "name": "AngryTools", "url": "https://angrytools.com/" },
        { "id": "freefrontend", "name": "Free Frontend", "url": "https://freefrontend.com/" },
        { "id": "mdn-docs", "name": "MDN Web Docs", "url": "https://developer.mozilla.org/en-US/" },
        { "id": "html-cheatsheet", "name": "HTML Cheatsheet", "url": "https://htmlcheatsheet.com/" },
        { "id": "jquery-ui", "name": "jQuery UI", "url": "https://jqueryui.com/" },
        { "id": "free-code-tools", "name": "Free Code Tools", "url": "https://freecodetools.org/" },
        { "id": "jquery-script", "name": "jQuery Script", "url": "https://www.jqueryscript.net/" },
        { "id": "graphql-to-typescript", "name": "GraphQL to TypeScript", "url": "https://transform.tools/graphql-to-typescript" },
        { "id": "carbon-now", "name": "Carbon (Code Snippets)", "url": "https://carbon.now.sh/" },
        { "id": "readme-so", "name": "README.so Editor", "url": "https://readme.so/editor" },
        { "id": "all-in-one-tools", "name": "All-In-One Tools", "url": "https://allinone.tools/" },
        { "id": "tint-mint", "name": "Tint Mint", "url": "https://tintmint.net/" },
        { "id": "boxshadows-xyz", "name": "BoxShadows.xyz", "url": "https://boxshadows.xyz/" },
        { "id": "ggradient", "name": "GGradient", "url": "https://ggradient.com/" },
        { "id": "flexer-dev", "name": "Flexer.dev", "url": "https://www.flexer.dev/" },
        { "id": "3d-book-generator", "name": "3D Book Generator", "url": "https://scastiel.dev/3dbook" },
        { "id": "vanta-js", "name": "Vanta.js (Animated Backgrounds)", "url": "https://www.vantajs.com/" },
        { "id": "naker-back", "name": "Naker Back", "url": "http://back.naker.io/" },
        { "id": "trianglify", "name": "Trianglify", "url": "https://trianglify.io/" },
        { "id": "pocoloco", "name": "PocoLoco", "url": "https://pocoloco.io/" },
        { "id": "web-gradients", "name": "WebGradients", "url": "https://webgradients.com/" },
        { "id": "excalidraw", "name": "Excalidraw", "url": "https://excalidraw.com/" },
        { "id": "truben-table", "name": "Truben Table Generator", "url": "https://truben.no/table/" },
        { "id": "markdown-table-generator", "name": "Markdown Table Generator", "url": "https://tableconvert.com/markdown-generator" },
        { "id": "tabulator", "name": "Tabulator", "url": "https://tabulator.info/" },
        { "id": "datatables", "name": "DataTables", "url": "https://datatables.net/" },
        { "id": "react-spreadsheet", "name": "React Spreadsheet", "url": "https://iddan.github.io/react-spreadsheet/storybook/?path=/story/spreadsheet--basic" },
        { "id": "trumbowyg", "name": "Trumbowyg (Editor)", "url": "https://alex-d.github.io/Trumbowyg/" },
        { "id": "edit-csv", "name": "Edit CSV", "url": "https://edit-csv.net/" },
        { "id": "10015-tools", "name": "10015.io All-in-one", "url": "https://10015.io/" },
        { "id": "1001-fonts", "name": "1001 Fonts", "url": "https://www.1001fonts.com/" },
        { "id": "unsplash", "name": "Unsplash", "url": "https://unsplash.com/" },
        { "id": "tutorialspoint-whiteboard", "name": "Tutorialspoint Whiteboard", "url": "https://www.tutorialspoint.com/whiteboard.htm" },
        { "id": "cool-symbol", "name": "CoolSymbol", "url": "https://coolsymbol.com/" },
        { "id": "webflow-templates", "name": "Webflow Templates", "url": "https://webflow.com/templates" },
        { "id": "codehim", "name": "CodeHim", "url": "https://www.codehim.com/" },
        { "id": "materialize-css", "name": "Materialize CSS", "url": "https://materializecss.com/" },
        { "id": "xmple-wallpaper", "name": "Xmple Wallpapers", "url": "https://xmple.com/wallpaper/" },
        { "id": "penpot", "name": "Penpot Design", "url": "https://design.penpot.app/" },
        { "id": "canva", "name": "Canva", "url": "https://www.canva.com/" },
        { "id": "temp-mail", "name": "Temp Mail", "url": "https://temp-mail.org/pl/" },
        { "id": "carrd", "name": "Carrd.co", "url": "https://carrd.co/" },
        { "id": "sumo-paint", "name": "Sumo Paint", "url": "https://paint.sumo.app/?lang=pl" },
        { "id": "fullpage-js", "name": "fullPage.js", "url": "https://alvarotrigo.com/fullPage/" },
        { "id": "bootsnipp", "name": "Bootsnipp", "url": "https://bootsnipp.com/" },
        { "id": "pattern-monster", "name": "Pattern Monster", "url": "https://pattern.monster/" },
        { "id": "fffuel", "name": "fffuel (SVG Tools)", "url": "https://www.fffuel.co/" },
        { "id": "gradient-buttons", "name": "Gradient Buttons", "url": "https://gradientbuttons.colorion.co/" },
        { "id": "cdnjs", "name": "cdnjs", "url": "https://cdnjs.com/" },
        { "id": "pixabay", "name": "Pixabay", "url": "https://pixabay.com/pl/" },
        { "id": "stocksnap", "name": "StockSnap", "url": "https://stocksnap.io/" },
        { "id": "pixlr-remove-bg", "name": "Pixlr Remove BG", "url": "https://pixlr.com/pl/remove-background/" }
    ]
};
